// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBolPQFbRNznzrkd37qiailUVDKZhxrASo',
    appId: '1:158994892323:web:d63afa946d85a41abd5396',
    messagingSenderId: '158994892323',
    projectId: 'summerterm-914c7',
    authDomain: 'summerterm-914c7.firebaseapp.com',
    databaseURL: 'https://summerterm-914c7-default-rtdb.firebaseio.com',
    storageBucket: 'summerterm-914c7.appspot.com',
    measurementId: 'G-FJP0ZFDH8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRzlcgkSg6ma9N0-hGv3LXwcTWd15oXgo',
    appId: '1:158994892323:android:d0bbd002588a5972bd5396',
    messagingSenderId: '158994892323',
    projectId: 'summerterm-914c7',
    databaseURL: 'https://summerterm-914c7-default-rtdb.firebaseio.com',
    storageBucket: 'summerterm-914c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Qid6ZQGmI__QjWYwnjlEZheZ0VYF0U4',
    appId: '1:158994892323:ios:33bdd36b21798847bd5396',
    messagingSenderId: '158994892323',
    projectId: 'summerterm-914c7',
    databaseURL: 'https://summerterm-914c7-default-rtdb.firebaseio.com',
    storageBucket: 'summerterm-914c7.appspot.com',
    iosBundleId: 'com.example.st',
  );
}
